// Generated by CoffeeScript 1.7.1
(function() {
  var AJSON;

  AJSON = (function() {
    function AJSON() {}

    AJSON.stringify = function(data, cb) {
      var result;
      result = JSON.stringify(data);
      return cb(null, result);
    };

    AJSON.parse = function(s, cb) {
      var e, err, result;
      try {
        result = JSON.parse(s);
      } catch (_error) {
        e = _error;
        err = new Error("Invalid JSON string provided");
        return cb(err, null);
      }
      return cb(null, result);
    };

    return AJSON;

  })();

  module.exports = AJSON;

}).call(this);
