// Generated by CoffeeScript 1.7.1
(function() {
  var AJSON, asyncJSON, es, resumer;

  asyncJSON = require("async-json");

  resumer = require("resumer");

  es = require("event-stream");

  AJSON = (function() {
    function AJSON() {}

    AJSON.stringify = function(data, cb) {
      return asyncJSON.stringify(data, function(err, result) {
        return cb(err, result);
      });
    };

    AJSON.parse = function(s, cb) {
      var stream;
      stream = resumer();
      stream.queue(s);
      return stream.pipe(es.parse({
        error: true
      })).on("error", function(theErr) {
        var err;
        err = new Error("Invalid JSON string provided");
        return cb(err, null);
      }).pipe(es.map(function(data, callback) {
        callback(null, data);
        return cb(null, data);
      }));
    };

    return AJSON;

  })();

  module.exports = AJSON;

}).call(this);
